-- records sales per transaction

CREATE TABLE vendas.tb_vendas (
ID_TRANSACAO BIGINT NOT NULL,
DATAHORATRANSACAO VARCHAR(25) NOT NULL,
TIPOPAGAMENTO VARCHAR(100) NOT NULL,
VL_VENDA FLOAT NOT NULL,
USR_VENDA VARCHAR(150) NOT NULL,
DT_VENDA DATE NOT NULL,
HR_VENDA TIME NOT NULL
);
